---
- name: Admin-Benutzername und Passwort festlegen
  set_fact:
    admin_user: "admin@kasm.local"
    admin_password: "{{ kasm_admin_password }}"
    skip_api: true

- name: KASM Docker-Netzwerk ermitteln
  shell: docker network ls | grep kasm | awk '{print $2}' | head -1
  register: kasm_networks
  changed_when: false

- name: KASM-Netzwerk festlegen
  set_fact:
    kasm_network: "{{ kasm_networks.stdout | default('bridge') }}"

- name: GitLab Workspace-Container pr체fen
  shell: docker ps -a --filter "name=kasm_custom_gitlab" -q
  register: docker_check
  changed_when: false

- name: Verf체gbare KASM-Images auflisten
  shell: docker images | grep kasmweb
  register: kasm_images
  changed_when: false

- name: KASM-Images anzeigen
  debug:
    var: kasm_images.stdout_lines

# Verwende ein vorhandenes Image f체r GitLab oder ein 채hnliches
- name: GitLab Workspace-Container starten
  shell: >
    docker run -d
    --name kasm_custom_gitlab
    --network {{ kasm_network }}
    --label "kasm.workspace=true"
    --label "kasm.workspace.name=GitLab"
    -e VNC_PW={{ kasm_user_password }}
    -e KASM_USER=kasm-user
    kasmweb/ubuntu-jammy-desktop:latest
  when: 
    - docker_check.stdout == ""
  ignore_errors: yes
  register: gitlab_container_result

- name: GitLab-Tools in Container installieren
  shell: >
    docker exec kasm_custom_gitlab bash -c "apt-get update &&
    apt-get install -y git curl ca-certificates gnupg &&
    curl -fsSL https://gitlab.com/gitlab-org/gitlab-ee/raw/master/scripts/gitlab-install.sh | bash"
  when: gitlab_container_result is not failed and gitlab_container_result.changed
  ignore_errors: yes

- name: Status-Info anzeigen
  debug:
    msg: "GitLab Workspace wurde als Ubuntu-Container mit GitLab-Tools eingerichtet."
