---
- name: Admin-Benutzername und Passwort festlegen (falls nicht vorhanden)
  set_fact:
    admin_user: "admin@kasm.local"
    admin_password: "{{ kasm_admin_password }}"
  when: admin_user is not defined or admin_password is not defined

- name: Token von KASM API bekommen
  uri:
    url: "{{ kasm_api_url }}/auth/login"
    method: POST
    validate_certs: no
    body_format: json
    body:
      username: "{{ admin_user }}"
      password: "{{ admin_password }}"
  register: token_result
  failed_when: false
  retries: 5
  delay: 10
  until: token_result.status == 200 or token_result.json is defined

- name: Token extrahieren
  set_fact:
    kasm_token: "{{ token_result.json.token }}"
  when: token_result.json is defined and token_result.json.token is defined

- name: Ansible Control-Node Workspace in KASM aktivieren
  uri:
    url: "{{ kasm_api_url }}/images"
    method: POST
    validate_certs: no
    headers:
      Authorization: "Bearer {{ kasm_token }}"
    body_format: json
    body:
      image_src: "docker.io/kasmweb/ubuntu-focal-desktop:latest"
      friendly_name: "Ansible Control Node"
      description: "Ubuntu mit vorinstalliertem Ansible für den Kurs"
      image_type: "container"
      enabled: true
      cpu_limit: 2
      memory_limit: 4096
      gpu_count: 0
      docker_registry: "https://index.docker.io/v1/"
      category: "Development"
      exec_config:
        startupScript: |
          apt-get update && 
          apt-get install -y ansible git python3-pip sshpass python3-paramiko &&
          mkdir -p /home/kasm-user/ansible/{playbooks,inventory,roles} &&
          chown -R kasm-user:kasm-user /home/kasm-user/ansible
  register: ansible_image_result
  failed_when: false
  when: kasm_token is defined

- name: Ansible Workspace-Status anzeigen
  debug:
    msg: >
      {% if ansible_image_result.status is defined and (ansible_image_result.status == 200 or ansible_image_result.status == 201) %}
      Ansible Control Node Workspace erfolgreich aktiviert
      {% else %}
      Konnte Ansible Workspace nicht aktivieren: {{ ansible_image_result.msg | default('Unbekannter Fehler') }}
      {% endif %}
  when: ansible_image_result is defined
